In [1]:
import pandas as pd

In [2]:
df_ret = pd.read_csv('MIS_1001_AUS_DSM_Retailer_list_Details_202505-UTF-8.csv', encoding='utf-8')
df5 = pd.read_csv('MIS_1001_AUS_MLY_RETAILER_20250525-UTF-8.csv', encoding='utf-8')
df6 = pd.read_csv('MIS_1001_AUS_MLY_RETAILER_20250625-UTF-8.csv', encoding='utf-8')
df7 = pd.read_csv('MIS_1001_AUS_MLY_RETAILER_20250725-UTF-8.csv', encoding='utf-8')
df8 = pd.read_csv('MIS_1001_AUS_MLY_RETAILER_20250825-UTF-8.csv', encoding='utf-8')
df9 = pd.read_csv('MIS_1001_AUS_MLY_RETAILER_20250925-UTF-8.csv', encoding='utf-8')

C:\Users\JD\AppData\Local\Temp\ipykernel_1468\3989781179.py:3: DtypeWarning: Columns (17,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df6 = pd.read_csv('MIS_1001_AUS_MLY_RETAILER_20250625-UTF-8.csv', encoding='utf-8')
C:\Users\JD\AppData\Local\Temp\ipykernel_1468\3989781179.py:4: DtypeWarning: Columns (17,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df7 = pd.read_csv('MIS_1001_AUS_MLY_RETAILER_20250725-UTF-8.csv', encoding='utf-8')
C:\Users\JD\AppData\Local\Temp\ipykernel_1468\3989781179.py:5: DtypeWarning: Columns (17,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df8 = pd.read_csv('MIS_1001_AUS_MLY_RETAILER_20250825-UTF-8.csv', encoding='utf-8')
C:\Users\JD\AppData\Local\Temp\ipykernel_1468\3989781179.py:6: DtypeWarning: Columns (17,21,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df9 = pd.read_csv('MIS_1001_AUS_MLY_RETAILER_20250925-UTF-8.csv', encoding='utf-8')

In [3]:

print(df_ret.shape)
print(df5.shape)
print(df6.shape)
print(df7.shape)
print(df8.shape)
print(df9.shape)

(25350, 30)
(734, 93)
(26087, 93)
(26088, 93)
(26090, 93)
(26088, 93)

In [4]:
df9.columns

Index(['ISSUE1_INVALID RETAILER STATUS', 'ISSUE2_INVALID RETAILER MODE',
       'ISSUE3_INVALID WHITELIST NUMBER', 'ISSUE4_INVALID VIRTUAL NUMBER',
       'ISSUE5_SIM BLOCKED', 'STARTDATE', 'ENDDATE', 'CREATEDBY',
       'DATEOFCREATION', 'OFFMGRID', 'ACCMGRID', 'HOTSPOTID', 'RETAILERID',
       'SHOPTYPE', 'CONTACTPERSON', 'FNAME', 'MOBILENO', 'LANDLINENO',
       'HOUSENO', 'STREET', 'CITY', 'POSTCODE', 'EMAIL', 'VAT_NO', 'RETID',
       'RETAILERMODE', 'RETAILER_STATUS', 'RETAILER_MSISDN', 'WHITEIST_STATUS',
       'REGISTRATIONS', 'TOTALSIM_TILLDATE', 'TOTALSIM_MONTH',
       'NOOFACTIVATIONS_ALL', 'NORMAL_NOOFACTIVATIONS', 'NORMAL_TOPUP_AMOUNT',
       'NORMAL_PRE_B1_AMOUNT', 'NORMAL_ELIGIBLE_AMOUNT',
       'NORMAL_PRE_B2_LESS30', 'NORMAL_PRE_B2_GRT30', 'NORMAL_PRE_B3_LESS30',
       'NORMAL_PRE_B3_GRT30', 'NORMAL_PRE_B4_LESS30', 'NORMAL_PRE_B4_GRT30',
       'NORMAL_ZERO_B1_OL_AMOUNT', 'NORMAL_ZERO_B2_OL_AMOUNT',
       'NORMAL_ZERO_B3_OL_AMOUNT', 'NORMAL_ZERO_B1_OFF_AMOUNT',
       'NORMAL_ZERO_B2_OFF_AMOUNT', 'NORMAL_ZERO_B3_OFF_AMOUNT',
       'BLOCKED_NOOFACTIVATIONS', 'BLOCKED_TOPUP_AMOUNT',
       'BLOCKED_PRE_B1_AMOUNT', 'BLOCKED_ELIGIBLE_AMOUNT',
       'BLOCKED_PRE_B2_LESS30', 'BLOCKED_PRE_B2_GRT30',
       'BLOCKED_PRE_B3_LESS30', 'BLOCKED_PRE_B3_GRT30',
       'BLOCKED_PRE_B4_LESS30', 'BLOCKED_PRE_B4_GRT30',
       'BLOCKED_ZERO_B1_OL_AMOUNT', 'BLOCKED_ZERO_B2_OL_AMOUNT',
       'BLOCKED_ZERO_B3_OL_AMOUNT', 'BLOCKED_ZERO_B1_OFF_AMOUNT',
       'BLOCKED_ZERO_B2_OFF_AMOUNT', 'BLOCKED_ZERO_B3_OFF_AMOUNT',
       'TOTAL_NOOFACTIVATIONS', 'TOTAL_TOPUP_AMOUNT', 'CALC_TOPUP1',
       'PRE_B1_AMOUNT', 'PRE_B2_LESS30', 'PRE_B2_GRT30', 'PRE_B3_LESS30',
       'PRE_B3_GRT30', 'PRE_B4_LESS30', 'PRE_B4_GRT30', 'ZERO_B1_OL_AMOUNT',
       'ZERO_B2_OL_AMOUNT', 'ZERO_B3_OL_AMOUNT', 'ZERO_B1_OFF_AMOUNT',
       'ZERO_B2_OFF_AMOUNT', 'ZERO_B3_OFF_AMOUNT', 'LAST_BUNDLE_COUNT', 'TIER',
       'ELIGIBLE_AMOUNT', 'LAST_MONTH_BUNDLE_ACTIVATION',
       'CURRENT_MONTH_RENEWAL', 'RENEWAL_PERCENTAGE', 'ACTIVATIONBONUS',
       'ZERO_BUNDLE_ONLINE_COMM', 'ZERO_BUNDLE_OFFLINE_COMM',
       'Onboarding_Incentive', 'BUNDLE_COMM', 'TOTAL_COMM'],
      dtype='object')

In [9]:
df_ret

,ISSUE1_INVALID RETAILER STATUS,ISSUE2_INVALID RETAILER MODE,ISSUE3_INVALID WHITELIST NUMBER,ISSUE4_INVALID VIRTUAL NUMBER,ISSUE5_SIM BLOCKED,STARTDATE,ENDDATE,CREATEDBY,DATEOFCREATION,OFFMGRID,...,CITY,POSTCODE,EMAIL,VAT_NO,RETID,RETAILERMODE,RETAILER_STATUS,RETAILER_MSISDN,WHITEIST_STATUS,REGISTRATIONS
0,NaN,NaN,NaN,NaN,NaN,20250426,20250525,PREM-EUROPEAN AGENCY,02-08-2019,LMAZ-HS-HEADOFFICE,...,PARRAMATTA,2150,info@brooklineconsult.com,NaN,NaN,VIRTUAL,ACTIVE,6.100269e+10,ACTIVE,NaN
1,NaN,NaN,NaN,NaN,NaN,20250426,20250525,LMAZ-SM-CHINESE,31-01-2023,LMAZ-SM-HEADOFFICE,...,Burwood,2134,chunmei.wang@lycamobile.com.au,NaN,NaN,0,ACTIVE,NaN,ACTIVE,NaN
2,NO,NO,NO,NO,YES,20250426,20250525,perthhotspotjessy,26-05-2012,LMAZ-HS-HEADOFFICE,...,Balcatta,6021,hasugohil@yahoo.com,NaN,1251.0,VIRTUAL,ACTIVE,6.100269e+10,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,20250426,20250525,perthhotspotjessy,21-12-2012,LMAZ-HS-HEADOFFICE,...,MIRRABOOKA,6061,NaN,NaN,3886.0,VIRTUAL,ACTIVE,6.100269e+10,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,20250426,20250525,HS_brisbane_zone1,25-11-2014,LMAZ-HS-HEADOFFICE,...,Brisbane,4001,NaN,NaN,NaN,VIRTUAL,ACTIVE,6.100268e+10,ACTIVE,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25345,NO,NO,NO,NO,YES,20250426,20250525,melhotspotswetha,05-11-2012,LMAZ-HS-HEADOFFICE,...,OAKLEIGH,3166,NaN,NaN,3233.0,VIRTUAL,ACTIVE,6.100268e+10,NaN,NaN
25346,NaN,NaN,NaN,NaN,NaN,20250426,20250525,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25347,NO,YES,NO,NO,NO,20250426,20250525,HS MELBOURNE ZONE 4,23-12-2022,LMAZ-HS-HEADOFFICE,...,Greensborough,3088,info@cityphones.com.au,70619946637,NaN,0,ACTIVE,NaN,ACTIVE,NaN
25348,NaN,NaN,NaN,NaN,NaN,20250426,20250525,dsmadmin,20-06-2014,LMAZ-HS-HEADOFFICE,...,Carlton,3053,NaN,NaN,NaN,VIRTUAL,INACTIVE,6.100268e+10,NaN,NaN
25349,NaN,NaN,NaN,NaN,NaN,20250426,20250525,priyantha-dsm,26-02-2020,LMAZ-HS-HEADOFFICE,...,MELBOURNE,3000,cityphonesinfo@gmail.com,NaN,NaN,VIRTUAL,ACTIVE,6.100269e+10,ACTIVE,NaN

In [10]:
df_ret.dtypes

ISSUE1_INVALID RETAILER STATUS      object
ISSUE2_INVALID RETAILER MODE        object
ISSUE3_INVALID WHITELIST NUMBER     object
ISSUE4_INVALID VIRTUAL NUMBER       object
ISSUE5_SIM BLOCKED                  object
STARTDATE                            int64
ENDDATE                              int64
CREATEDBY                           object
DATEOFCREATION                      object
OFFMGRID                            object
ACCMGRID                            object
HOTSPOTID                           object
RETAILERID                          object
SHOPTYPE                            object
CONTACTPERSON                       object
FNAME                               object
MOBILENO                            object
LANDLINENO                          object
HOUSENO                             object
STREET                              object
CITY                                object
POSTCODE                            object
EMAIL                               object
VAT_NO                              object
RETID                              float64
RETAILERMODE                        object
RETAILER_STATUS                     object
RETAILER_MSISDN                    float64
WHITEIST_STATUS                     object
REGISTRATIONS                      float64
dtype: object

In [12]:
df9.dtypes

ISSUE1_INVALID RETAILER STATUS      object
ISSUE2_INVALID RETAILER MODE        object
ISSUE3_INVALID WHITELIST NUMBER     object
ISSUE4_INVALID VIRTUAL NUMBER       object
ISSUE5_SIM BLOCKED                  object
                                    ...
ZERO_BUNDLE_ONLINE_COMM            float64
ZERO_BUNDLE_OFFLINE_COMM           float64
Onboarding_Incentive                 int64
BUNDLE_COMM                        float64
TOTAL_COMM                         float64
Length: 93, dtype: object

In [25]:
df9.isnull().sum()

ISSUE1_INVALID RETAILER STATUS     22894
ISSUE2_INVALID RETAILER MODE       22894
ISSUE3_INVALID WHITELIST NUMBER    22894
ISSUE4_INVALID VIRTUAL NUMBER      22894
ISSUE5_SIM BLOCKED                 22894
                                   ...
ZERO_BUNDLE_ONLINE_COMM                0
ZERO_BUNDLE_OFFLINE_COMM               0
Onboarding_Incentive                   0
BUNDLE_COMM                            0
TOTAL_COMM                             0
Length: 93, dtype: int64

In [39]:
len(df9)

26088

In [37]:
for column in df9:
    print("====================================================")
    print(f"====================={column}==========================")
    print("====================================================")
    
    print( f"df5 :" ,df5[column].isnull().sum(), f".df6 :" ,df6[column].isnull().sum(),
              f".df7 :" ,df7[column].isnull().sum(),f".df8 :" ,df8[column].isnull().sum(),f".df9 :" ,df9[column].isnull().sum())

====================================================
=====================ISSUE1_INVALID RETAILER STATUS==========================
====================================================
df5 : 423 .df6 : 22892 .df7 : 22893 .df8 : 22895 .df9 : 22894
====================================================
=====================ISSUE2_INVALID RETAILER MODE==========================
====================================================
df5 : 423 .df6 : 22892 .df7 : 22893 .df8 : 22895 .df9 : 22894
====================================================
=====================ISSUE3_INVALID WHITELIST NUMBER==========================
====================================================
df5 : 423 .df6 : 22892 .df7 : 22893 .df8 : 22895 .df9 : 22894
====================================================
=====================ISSUE4_INVALID VIRTUAL NUMBER==========================
====================================================
df5 : 423 .df6 : 22892 .df7 : 22893 .df8 : 22895 .df9 : 22894
====================================================
=====================ISSUE5_SIM BLOCKED==========================
====================================================
df5 : 423 .df6 : 22892 .df7 : 22893 .df8 : 22895 .df9 : 22894
====================================================
=====================STARTDATE==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================ENDDATE==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================CREATEDBY==========================
====================================================
df5 : 1 .df6 : 6121 .df7 : 6121 .df8 : 6123 .df9 : 6121
====================================================
=====================DATEOFCREATION==========================
====================================================
df5 : 0 .df6 : 923 .df7 : 923 .df8 : 925 .df9 : 923
====================================================
=====================OFFMGRID==========================
====================================================
df5 : 0 .df6 : 923 .df7 : 923 .df8 : 925 .df9 : 923
====================================================
=====================ACCMGRID==========================
====================================================
df5 : 1 .df6 : 7007 .df7 : 7007 .df8 : 7009 .df9 : 7007
====================================================
=====================HOTSPOTID==========================
====================================================
df5 : 0 .df6 : 953 .df7 : 953 .df8 : 955 .df9 : 953
====================================================
=====================RETAILERID==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================SHOPTYPE==========================
====================================================
df5 : 3 .df6 : 940 .df7 : 940 .df8 : 942 .df9 : 940
====================================================
=====================CONTACTPERSON==========================
====================================================
df5 : 0 .df6 : 927 .df7 : 927 .df8 : 929 .df9 : 927
====================================================
=====================FNAME==========================
====================================================
df5 : 0 .df6 : 923 .df7 : 923 .df8 : 925 .df9 : 923
====================================================
=====================MOBILENO==========================
====================================================
df5 : 31 .df6 : 8387 .df7 : 8387 .df8 : 8389 .df9 : 8387
====================================================
=====================LANDLINENO==========================
====================================================
df5 : 30 .df6 : 4887 .df7 : 4887 .df8 : 4889 .df9 : 4887
====================================================
=====================HOUSENO==========================
====================================================
df5 : 24 .df6 : 1054 .df7 : 1054 .df8 : 1056 .df9 : 1054
====================================================
=====================STREET==========================
====================================================
df5 : 0 .df6 : 926 .df7 : 926 .df8 : 928 .df9 : 926
====================================================
=====================CITY==========================
====================================================
df5 : 0 .df6 : 924 .df7 : 924 .df8 : 926 .df9 : 924
====================================================
=====================POSTCODE==========================
====================================================
df5 : 0 .df6 : 924 .df7 : 924 .df8 : 926 .df9 : 924
====================================================
=====================EMAIL==========================
====================================================
df5 : 98 .df6 : 19447 .df7 : 19447 .df8 : 19449 .df9 : 19447
====================================================
=====================VAT_NO==========================
====================================================
df5 : 497 .df6 : 24140 .df7 : 24140 .df8 : 24142 .df9 : 24140
====================================================
=====================RETID==========================
====================================================
df5 : 519 .df6 : 19253 .df7 : 19254 .df8 : 19256 .df9 : 19254
====================================================
=====================RETAILERMODE==========================
====================================================
df5 : 0 .df6 : 923 .df7 : 923 .df8 : 925 .df9 : 923
====================================================
=====================RETAILER_STATUS==========================
====================================================
df5 : 0 .df6 : 923 .df7 : 923 .df8 : 925 .df9 : 923
====================================================
=====================RETAILER_MSISDN==========================
====================================================
df5 : 162 .df6 : 12706 .df7 : 12706 .df8 : 12708 .df9 : 12705
====================================================
=====================WHITEIST_STATUS==========================
====================================================
df5 : 195 .df6 : 13470 .df7 : 13470 .df8 : 13472 .df9 : 13469
====================================================
=====================REGISTRATIONS==========================
====================================================
df5 : 734 .df6 : 26087 .df7 : 26088 .df8 : 26090 .df9 : 26088
====================================================
=====================TOTALSIM_TILLDATE==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================TOTALSIM_MONTH==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================NOOFACTIVATIONS_ALL==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================NORMAL_NOOFACTIVATIONS==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================NORMAL_TOPUP_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================NORMAL_PRE_B1_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================NORMAL_ELIGIBLE_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================NORMAL_PRE_B2_LESS30==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================NORMAL_PRE_B2_GRT30==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================NORMAL_PRE_B3_LESS30==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================NORMAL_PRE_B3_GRT30==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================NORMAL_PRE_B4_LESS30==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================NORMAL_PRE_B4_GRT30==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================NORMAL_ZERO_B1_OL_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================NORMAL_ZERO_B2_OL_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================NORMAL_ZERO_B3_OL_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================NORMAL_ZERO_B1_OFF_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================NORMAL_ZERO_B2_OFF_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================NORMAL_ZERO_B3_OFF_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================BLOCKED_NOOFACTIVATIONS==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================BLOCKED_TOPUP_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================BLOCKED_PRE_B1_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================BLOCKED_ELIGIBLE_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================BLOCKED_PRE_B2_LESS30==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================BLOCKED_PRE_B2_GRT30==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================BLOCKED_PRE_B3_LESS30==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================BLOCKED_PRE_B3_GRT30==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================BLOCKED_PRE_B4_LESS30==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================BLOCKED_PRE_B4_GRT30==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================BLOCKED_ZERO_B1_OL_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================BLOCKED_ZERO_B2_OL_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================BLOCKED_ZERO_B3_OL_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================BLOCKED_ZERO_B1_OFF_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================BLOCKED_ZERO_B2_OFF_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================BLOCKED_ZERO_B3_OFF_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================TOTAL_NOOFACTIVATIONS==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================TOTAL_TOPUP_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================CALC_TOPUP1==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================PRE_B1_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================PRE_B2_LESS30==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================PRE_B2_GRT30==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================PRE_B3_LESS30==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================PRE_B3_GRT30==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================PRE_B4_LESS30==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================PRE_B4_GRT30==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================ZERO_B1_OL_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================ZERO_B2_OL_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================ZERO_B3_OL_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================ZERO_B1_OFF_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================ZERO_B2_OFF_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================ZERO_B3_OFF_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================LAST_BUNDLE_COUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================TIER==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================ELIGIBLE_AMOUNT==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================LAST_MONTH_BUNDLE_ACTIVATION==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================CURRENT_MONTH_RENEWAL==========================
====================================================
df5 : 65 .df6 : 126 .df7 : 158 .df8 : 155 .df9 : 152
====================================================
=====================RENEWAL_PERCENTAGE==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================ACTIVATIONBONUS==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================ZERO_BUNDLE_ONLINE_COMM==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================ZERO_BUNDLE_OFFLINE_COMM==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================
=====================Onboarding_Incentive==========================
====================================================
df5 : 0 .df6 : 0 .df7 : 0 .df8 : 2 .df9 : 0
====================================================

In [38]:
# Let's assume your DataFrames are named df5, df6, df7, df8, df9

dataframes = {
    'df5': df5,
    'df6': df6,
    'df7': df7,
    'df8': df8,
    'df9': df9
}

# Loop through each column (assuming all dataframes share the same columns)
for column in df9.columns:
    print("=" * 80)
    print(f"{column:^80}")   # nicely centered column name
    print("=" * 80)
    
    for name, df in dataframes.items():
        total_rows = len(df)
        null_count = df[column].isnull().sum()
        null_percent = (null_count / total_rows) * 100
        
        print(f"{name:<5} → Rows: {total_rows:<7} | Nulls: {null_count:<6} | "
              f"Missing %: {null_percent:6.2f}%")
    
    print("\n")

================================================================================
                         ISSUE1_INVALID RETAILER STATUS
================================================================================
df5   → Rows: 734     | Nulls: 423    | Missing %:  57.63%
df6   → Rows: 26087   | Nulls: 22892  | Missing %:  87.75%
df7   → Rows: 26088   | Nulls: 22893  | Missing %:  87.75%
df8   → Rows: 26090   | Nulls: 22895  | Missing %:  87.75%
df9   → Rows: 26088   | Nulls: 22894  | Missing %:  87.76%


================================================================================
                          ISSUE2_INVALID RETAILER MODE
================================================================================
df5   → Rows: 734     | Nulls: 423    | Missing %:  57.63%
df6   → Rows: 26087   | Nulls: 22892  | Missing %:  87.75%
df7   → Rows: 26088   | Nulls: 22893  | Missing %:  87.75%
df8   → Rows: 26090   | Nulls: 22895  | Missing %:  87.75%
df9   → Rows: 26088   | Nulls: 22894  | Missing %:  87.76%


================================================================================
                        ISSUE3_INVALID WHITELIST NUMBER
================================================================================
df5   → Rows: 734     | Nulls: 423    | Missing %:  57.63%
df6   → Rows: 26087   | Nulls: 22892  | Missing %:  87.75%
df7   → Rows: 26088   | Nulls: 22893  | Missing %:  87.75%
df8   → Rows: 26090   | Nulls: 22895  | Missing %:  87.75%
df9   → Rows: 26088   | Nulls: 22894  | Missing %:  87.76%


================================================================================
                         ISSUE4_INVALID VIRTUAL NUMBER
================================================================================
df5   → Rows: 734     | Nulls: 423    | Missing %:  57.63%
df6   → Rows: 26087   | Nulls: 22892  | Missing %:  87.75%
df7   → Rows: 26088   | Nulls: 22893  | Missing %:  87.75%
df8   → Rows: 26090   | Nulls: 22895  | Missing %:  87.75%
df9   → Rows: 26088   | Nulls: 22894  | Missing %:  87.76%


================================================================================
                               ISSUE5_SIM BLOCKED
================================================================================
df5   → Rows: 734     | Nulls: 423    | Missing %:  57.63%
df6   → Rows: 26087   | Nulls: 22892  | Missing %:  87.75%
df7   → Rows: 26088   | Nulls: 22893  | Missing %:  87.75%
df8   → Rows: 26090   | Nulls: 22895  | Missing %:  87.75%
df9   → Rows: 26088   | Nulls: 22894  | Missing %:  87.76%


================================================================================
                                   STARTDATE
================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00%
df6   → Rows: 26087   | Nulls: 0      | Missing %:   0.00%
df7   → Rows: 26088   | Nulls: 0      | Missing %:   0.00%
df8   → Rows: 26090   | Nulls: 2      | Missing %:   0.01%
df9   → Rows: 26088   | Nulls: 0      | Missing %:   0.00%


================================================================================
                                    ENDDATE
================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00%
df6   → Rows: 26087   | Nulls: 0      | Missing %:   0.00%
df7   → Rows: 26088   | Nulls: 0      | Missing %:   0.00%
df8   → Rows: 26090   | Nulls: 2      | Missing %:   0.01%
df9   → Rows: 26088   | Nulls: 0      | Missing %:   0.00%


================================================================================
                                   CREATEDBY
================================================================================
df5   → Rows: 734     | Nulls: 1      | Missing %:   0.14%
df6   → Rows: 26087   | Nulls: 6121   | Missing %:  23.46%
df7   → Rows: 26088   | Nulls: 6121   | Missing %:  23.46%
df8   → Rows: 26090   | Nulls: 6123   | Missing %:  23.47%
df9   → Rows: 26088   | Nulls: 6121   | Missing %:  23.46%


================================================================================
                                 DATEOFCREATION
================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00%
df6   → Rows: 26087   | Nulls: 923    | Missing %:   3.54%
df7   → Rows: 26088   | Nulls: 923    | Missing %:   3.54%
df8   → Rows: 26090   | Nulls: 925    | Missing %:   3.55%
df9   → Rows: 26088   | Nulls: 923    | Missing %:   3.54%


================================================================================
                                    OFFMGRID
================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00%
df6   → Rows: 26087   | Nulls: 923    | Missing %:   3.54%
df7   → Rows: 26088   | Nulls: 923    | Missing %:   3.54%
df8   → Rows: 26090   | Nulls: 925    | Missing %:   3.55%
df9   → Rows: 26088   | Nulls: 923    | Missing %:   3.54%


================================================================================
                                    ACCMGRID
================================================================================
df5   → Rows: 734     | Nulls: 1      | Missing %:   0.14%
df6   → Rows: 26087   | Nulls: 7007   | Missing %:  26.86%
df7   → Rows: 26088   | Nulls: 7007   | Missing %:  26.86%
df8   → Rows: 26090   | Nulls: 7009   | Missing %:  26.86%
df9   → Rows: 26088   | Nulls: 7007   | Missing %:  26.86%


================================================================================
                                   HOTSPOTID
================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00%
df6   → Rows: 26087   | Nulls: 953    | Missing %:   3.65%
df7   → Rows: 26088   | Nulls: 953    | Missing %:   3.65%
df8   → Rows: 26090   | Nulls: 955    | Missing %:   3.66%
df9   → Rows: 26088   | Nulls: 953    | Missing %:   3.65%


================================================================================
                                   RETAILERID
================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00%
df6   → Rows: 26087   | Nulls: 0      | Missing %:   0.00%
df7   → Rows: 26088   | Nulls: 0      | Missing %:   0.00%
df8   → Rows: 26090   | Nulls: 2      | Missing %:   0.01%
df9   → Rows: 26088   | Nulls: 0      | Missing %:   0.00%


================================================================================
                                    SHOPTYPE
================================================================================
df5   → Rows: 734     | Nulls: 3      | Missing %:   0.41%
df6   → Rows: 26087   | Nulls: 940    | Missing %:   3.60%
df7   → Rows: 26088   | Nulls: 940    | Missing %:   3.60%
df8   → Rows: 26090   | Nulls: 942    | Missing %:   3.61%
df9   → Rows: 26088   | Nulls: 940    | Missing %:   3.60%


================================================================================
                                 CONTACTPERSON
================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00%
df6   → Rows: 26087   | Nulls: 927    | Missing %:   3.55%
df7   → Rows: 26088   | Nulls: 927    | Missing %:   3.55%
df8   → Rows: 26090   | Nulls: 929    | Missing %:   3.56%
df9   → Rows: 26088   | Nulls: 927    | Missing %:   3.55%


================================================================================
                                     FNAME
================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00%
df6   → Rows: 26087   | Nulls: 923    | Missing %:   3.54%
df7   → Rows: 26088   | Nulls: 923    | Missing %:   3.54%
df8   → Rows: 26090   | Nulls: 925    | Missing %:   3.55%
df9   → Rows: 26088   | Nulls: 923    | Missing %:   3.54%


================================================================================
                                    MOBILENO
================================================================================
df5   → Rows: 734     | Nulls: 31     | Missing %:   4.22%
df6   → Rows: 26087   | Nulls: 8387   | Missing %:  32.15%
df7   → Rows: 26088   | Nulls: 8387   | Missing %:  32.15%
df8   → Rows: 26090   | Nulls: 8389   | Missing %:  32.15%
df9   → Rows: 26088   | Nulls: 8387   | Missing %:  32.15%


================================================================================
                                   LANDLINENO
================================================================================
df5   → Rows: 734     | Nulls: 30     | Missing %:   4.09%
df6   → Rows: 26087   | Nulls: 4887   | Missing %:  18.73%
df7   → Rows: 26088   | Nulls: 4887   | Missing %:  18.73%
df8   → Rows: 26090   | Nulls: 4889   | Missing %:  18.74%
df9   → Rows: 26088   | Nulls: 4887   | Missing %:  18.73%


================================================================================
                                    HOUSENO
================================================================================
df5   → Rows: 734     | Nulls: 24     | Missing %:   3.27%
df6   → Rows: 26087   | Nulls: 1054   | Missing %:   4.04%
df7   → Rows: 26088   | Nulls: 1054   | Missing %:   4.04%
df8   → Rows: 26090   | Nulls: 1056   | Missing %:   4.05%
df9   → Rows: 26088   | Nulls: 1054   | Missing %:   4.04%


================================================================================
                                     STREET
================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00%
df6   → Rows: 26087   | Nulls: 926    | Missing %:   3.55%
df7   → Rows: 26088   | Nulls: 926    | Missing %:   3.55%
df8   → Rows: 26090   | Nulls: 928    | Missing %:   3.56%
df9   → Rows: 26088   | Nulls: 926    | Missing %:   3.55%


================================================================================
                                      CITY
================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00%
df6   → Rows: 26087   | Nulls: 924    | Missing %:   3.54%
df7   → Rows: 26088   | Nulls: 924    | Missing %:   3.54%
df8   → Rows: 26090   | Nulls: 926    | Missing %:   3.55%
df9   → Rows: 26088   | Nulls: 924    | Missing %:   3.54%


================================================================================
                                    POSTCODE
================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00%
df6   → Rows: 26087   | Nulls: 924    | Missing %:   3.54%
df7   → Rows: 26088   | Nulls: 924    | Missing %:   3.54%
df8   → Rows: 26090   | Nulls: 926    | Missing %:   3.55%
df9   → Rows: 26088   | Nulls: 924    | Missing %:   3.54%


================================================================================
                                     EMAIL
================================================================================
df5   → Rows: 734     | Nulls: 98     | Missing %:  13.35%
df6   → Rows: 26087   | Nulls: 19447  | Missing %:  74.55%
df7   → Rows: 26088   | Nulls: 19447  | Missing %:  74.54%
df8   → Rows: 26090   | Nulls: 19449  | Missing %:  74.55%
df9   → Rows: 26088   | Nulls: 19447  | Missing %:  74.54%


================================================================================
                                     VAT_NO
================================================================================
df5   → Rows: 734     | Nulls: 497    | Missing %:  67.71%
df6   → Rows: 26087   | Nulls: 24140  | Missing %:  92.54%
df7   → Rows: 26088   | Nulls: 24140  | Missing %:  92.53%
df8   → Rows: 26090   | Nulls: 24142  | Missing %:  92.53%
df9   → Rows: 26088   | Nulls: 24140  | Missing %:  92.53%


================================================================================
                                     RETID
================================================================================
df5   → Rows: 734     | Nulls: 519    | Missing %:  70.71%
df6   → Rows: 26087   | Nulls: 19253  | Missing %:  73.80%
df7   → Rows: 26088   | Nulls: 19254  | Missing %:  73.80%
df8   → Rows: 26090   | Nulls: 19256  | Missing %:  73.81%
df9   → Rows: 26088   | Nulls: 19254  | Missing %:  73.80%


================================================================================
                                  RETAILERMODE
================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00%
df6   → Rows: 26087   | Nulls: 923    | Missing %:   3.54%
df7   → Rows: 26088   | Nulls: 923    | Missing %:   3.54%
df8   → Rows: 26090   | Nulls: 925    | Missing %:   3.55%
df9   → Rows: 26088   | Nulls: 923    | Missing %:   3.54%


================================================================================
                                RETAILER_STATUS
================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00%
df6   → Rows: 26087   | Nulls: 923    | Missing %:   3.54%
df7   → Rows: 26088   | Nulls: 923    | Missing %:   3.54%
df8   → Rows: 26090   | Nulls: 925    | Missing %:   3.55%
df9   → Rows: 26088   | Nulls: 923    | Missing %:   3.54%


================================================================================
                                RETAILER_MSISDN
================================================================================
df5   → Rows: 734     | Nulls: 162    | Missing %:  22.07%
df6   → Rows: 26087   | Nulls: 12706  | Missing %:  48.71%
df7   → Rows: 26088   | Nulls: 12706  | Missing %:  48.70%
df8   → Rows: 26090   | Nulls: 12708  | Missing %:  48.71%
df9   → Rows: 26088   | Nulls: 12705  | Missing %:  48.70%


================================================================================
                                WHITEIST_STATUS
================================================================================
df5   → Rows: 734     | Nulls: 195    | Missing %:  26.57%
df6   → Rows: 26087   | Nulls: 13470  | Missing %:  51.63%
df7   → Rows: 26088   | Nulls: 13470  | Missing %:  51.63%
df8   → Rows: 26090   | Nulls: 13472  | Missing %:  51.64%
df9   → Rows: 26088   | Nulls: 13469  | Missing %:  51.63%


================================================================================
                                 REGISTRATIONS
================================================================================
df5   → Rows: 734     | Nulls: 734    | Missing %: 100.00%
df6   → Rows: 26087   | Nulls: 26087  | Missing %: 100.00%
df7   → Rows: 26088   | Nulls: 26088  | Missing %: 100.00%
df8   → Rows: 26090   | Nulls: 26090  | Missing %: 100.00%
df9   → Rows: 26088   | Nulls: 26088  | Missing %: 100.00%


================================================================================
                               TOTALSIM_TILLDATE
================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00%
df6   → Rows: 26087   | Nulls: 0      | Missing %:   0.00%
df7   → Rows: 26088   | Nulls: 0      | Missing %:   0.00%
df8   → Rows: 26090   | Nulls: 2      | Missing %:   0.01%
df9   → Rows: 26088   | Nulls: 0      | Missing %:   0.00%


================================================================================
                                 TOTALSIM_MONTH
================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00%
df6   → Rows: 26087   | Nulls: 0      | Missing %:   0.00%
df7   → Rows: 26088   | Nulls: 0      | Missing %:   0.00%
df8   → Rows: 26090   | Nulls: 2      | Missing %:   0.01%
df9   → Rows: 26088   | Nulls: 0      | Missing %:   0.00%


================================================================================
                              NOOFACTIVATIONS_ALL
================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00%
df6   → Rows: 26087   | Nulls: 0      | Missing %:   0.00%
df7   → Rows: 26088   | Nulls: 0      | Missing %:   0.00%
df8   → Rows: 26090   | Nulls: 2      | Missing %:   0.01%
df9   → Rows: 26088   | Nulls: 0      | Missing %:   0.00%


================================================================================
                             NORMAL_NOOFACTIVATIONS
================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00%
df6   → Rows: 26087   | Nulls: 0      | Missing %:   0.00%
df7   → Rows: 26088   | Nulls: 0      | Missing %:   0.00%
df8   → Rows: 26090   | Nulls: 2      | Missing %:   0.01%
df9   → Rows: 26088   | Nulls: 0      | Missing %:   0.00%


================================================================================
                              NORMAL_TOPUP_AMOUNT
================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00%
df6   → Rows: 26087   | Nulls: 0      | Missing %:   0.00%
df7   → Rows: 26088   | Nulls: 0      | Missing %:   0.00%
df8   → Rows: 26090   | Nulls: 2      | Missing %:   0.01%
df9   → Rows: 26088   | Nulls: 0      | Missing %:   0.00%


================================================================================
                              NORMAL_PRE_B1_AMOUNT
================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00%
df6   → Rows: 26087   | Nulls: 0      | Missing %:   0.00%
df7   → Rows: 26088   | Nulls: 0      | Missing %:   0.00%
df8   → Rows: 26090   | Nulls: 2      | Missing %:   0.01%
df9   → Rows: 26088   | Nulls: 0      | Missing %:   0.00%


================================================================================
                             NORMAL_ELIGIBLE_AMOUNT
================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00%
df6   → Rows: 26087   | Nulls: 0      | Missing %:   0.00%
df7   → Rows: 26088   | Nulls: 0      | Missing %:   0.00%
df8   → Rows: 26090   | Nulls: 2      | Missing %:   0.01%
df9   → Rows: 26088   | Nulls: 0      | Missing %:   0.00%


================================================================================
                              NORMAL_PRE_B2_LESS30
================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00%
df6   → Rows: 26087   | Nulls: 0      | Missing %:   0.00%
df7   → Rows: 26088   | Nulls: 0      | Missing %:   0.00%
df8   → Rows: 26090   | Nulls: 2      | Missing %:   0.01%
df9   → Rows: 26088   | Nulls: 0      | Missing %:   0.00%


================================================================================
                              NORMAL_PRE_B2_GRT30
================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00%
df6   → Rows: 26087   | Nulls: 0      | Missing %:   0.00%
df7   → Rows: 26088   | Nulls: 0      | Missing %:   0.00%
df8   → Rows: 26090   | Nulls: 2      | Missing %:   0.01%
df9   → Rows: 26088   | Nulls: 0      | Missing %:   0.00%


================================================================================
                              NORMAL_PRE_B3_LESS30
================================================================================

In [46]:
# Let's assume your DataFrames are named df5, df6, df7, df8, df9

dataframes = {
    'df5': df5,
    'df6': df6,
    'df7': df7,
    'df8': df8,
    'df9': df9
}

# Loop through each column (assuming all dataframes share the same columns)
for column in df9.columns:
    print("=" * 90)
    print(f"{column:^90}")   # nicely centered column name
    print("=" * 90)
    
    # Print column's data type and unique value count from one reference df
    dtype = df9[column].dtype
    unique_values = df9[column].nunique(dropna=True)
    print(f"Data Type: {dtype} | Unique Values: {unique_values}")
    print("-" * 90)
    
    for name, df in dataframes.items():
        total_rows = len(df)
        null_count = df[column].isnull().sum()
        null_percent = (null_count / total_rows) * 100
        
        print(f"{name:<5} → Rows: {total_rows:<7} | Nulls: {null_count:<6} | "
              f"Missing %: {null_percent:6.2f}% | Unique: {df[column].nunique(dropna=True)}")
    
    print("\n")

==========================================================================================
                              ISSUE1_INVALID RETAILER STATUS
==========================================================================================
Data Type: object | Unique Values: 2
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 423    | Missing %:  57.63% | Unique: 2
df6   → Rows: 26087   | Nulls: 22892  | Missing %:  87.75% | Unique: 2
df7   → Rows: 26088   | Nulls: 22893  | Missing %:  87.75% | Unique: 2
df8   → Rows: 26090   | Nulls: 22895  | Missing %:  87.75% | Unique: 2
df9   → Rows: 26088   | Nulls: 22894  | Missing %:  87.76% | Unique: 2


==========================================================================================
                               ISSUE2_INVALID RETAILER MODE
==========================================================================================
Data Type: object | Unique Values: 2
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 423    | Missing %:  57.63% | Unique: 2
df6   → Rows: 26087   | Nulls: 22892  | Missing %:  87.75% | Unique: 2
df7   → Rows: 26088   | Nulls: 22893  | Missing %:  87.75% | Unique: 2
df8   → Rows: 26090   | Nulls: 22895  | Missing %:  87.75% | Unique: 2
df9   → Rows: 26088   | Nulls: 22894  | Missing %:  87.76% | Unique: 2


==========================================================================================
                             ISSUE3_INVALID WHITELIST NUMBER
==========================================================================================
Data Type: object | Unique Values: 1
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 423    | Missing %:  57.63% | Unique: 1
df6   → Rows: 26087   | Nulls: 22892  | Missing %:  87.75% | Unique: 1
df7   → Rows: 26088   | Nulls: 22893  | Missing %:  87.75% | Unique: 1
df8   → Rows: 26090   | Nulls: 22895  | Missing %:  87.75% | Unique: 1
df9   → Rows: 26088   | Nulls: 22894  | Missing %:  87.76% | Unique: 1


==========================================================================================
                              ISSUE4_INVALID VIRTUAL NUMBER
==========================================================================================
Data Type: object | Unique Values: 2
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 423    | Missing %:  57.63% | Unique: 2
df6   → Rows: 26087   | Nulls: 22892  | Missing %:  87.75% | Unique: 2
df7   → Rows: 26088   | Nulls: 22893  | Missing %:  87.75% | Unique: 2
df8   → Rows: 26090   | Nulls: 22895  | Missing %:  87.75% | Unique: 2
df9   → Rows: 26088   | Nulls: 22894  | Missing %:  87.76% | Unique: 2


==========================================================================================
                                    ISSUE5_SIM BLOCKED
==========================================================================================
Data Type: object | Unique Values: 2
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 423    | Missing %:  57.63% | Unique: 2
df6   → Rows: 26087   | Nulls: 22892  | Missing %:  87.75% | Unique: 2
df7   → Rows: 26088   | Nulls: 22893  | Missing %:  87.75% | Unique: 2
df8   → Rows: 26090   | Nulls: 22895  | Missing %:  87.75% | Unique: 2
df9   → Rows: 26088   | Nulls: 22894  | Missing %:  87.76% | Unique: 2


==========================================================================================
                                        STARTDATE
==========================================================================================
Data Type: int64 | Unique Values: 1
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00% | Unique: 1
df6   → Rows: 26087   | Nulls: 0      | Missing %:   0.00% | Unique: 1
df7   → Rows: 26088   | Nulls: 0      | Missing %:   0.00% | Unique: 1
df8   → Rows: 26090   | Nulls: 2      | Missing %:   0.01% | Unique: 1
df9   → Rows: 26088   | Nulls: 0      | Missing %:   0.00% | Unique: 1


==========================================================================================
                                         ENDDATE
==========================================================================================
Data Type: int64 | Unique Values: 1
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00% | Unique: 1
df6   → Rows: 26087   | Nulls: 0      | Missing %:   0.00% | Unique: 1
df7   → Rows: 26088   | Nulls: 0      | Missing %:   0.00% | Unique: 1
df8   → Rows: 26090   | Nulls: 2      | Missing %:   0.01% | Unique: 1
df9   → Rows: 26088   | Nulls: 0      | Missing %:   0.00% | Unique: 1


==========================================================================================
                                        CREATEDBY
==========================================================================================
Data Type: object | Unique Values: 159
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 1      | Missing %:   0.14% | Unique: 72
df6   → Rows: 26087   | Nulls: 6121   | Missing %:  23.46% | Unique: 159
df7   → Rows: 26088   | Nulls: 6121   | Missing %:  23.46% | Unique: 159
df8   → Rows: 26090   | Nulls: 6123   | Missing %:  23.47% | Unique: 159
df9   → Rows: 26088   | Nulls: 6121   | Missing %:  23.46% | Unique: 159


==========================================================================================
                                      DATEOFCREATION
==========================================================================================
Data Type: object | Unique Values: 1881
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00% | Unique: 504
df6   → Rows: 26087   | Nulls: 923    | Missing %:   3.54% | Unique: 1881
df7   → Rows: 26088   | Nulls: 923    | Missing %:   3.54% | Unique: 1881
df8   → Rows: 26090   | Nulls: 925    | Missing %:   3.55% | Unique: 1881
df9   → Rows: 26088   | Nulls: 923    | Missing %:   3.54% | Unique: 1881


==========================================================================================
                                         OFFMGRID
==========================================================================================
Data Type: object | Unique Values: 9
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00% | Unique: 3
df6   → Rows: 26087   | Nulls: 923    | Missing %:   3.54% | Unique: 9
df7   → Rows: 26088   | Nulls: 923    | Missing %:   3.54% | Unique: 9
df8   → Rows: 26090   | Nulls: 925    | Missing %:   3.55% | Unique: 9
df9   → Rows: 26088   | Nulls: 923    | Missing %:   3.54% | Unique: 9


==========================================================================================
                                         ACCMGRID
==========================================================================================
Data Type: object | Unique Values: 24
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 1      | Missing %:   0.14% | Unique: 6
df6   → Rows: 26087   | Nulls: 7007   | Missing %:  26.86% | Unique: 24
df7   → Rows: 26088   | Nulls: 7007   | Missing %:  26.86% | Unique: 24
df8   → Rows: 26090   | Nulls: 7009   | Missing %:  26.86% | Unique: 24
df9   → Rows: 26088   | Nulls: 7007   | Missing %:  26.86% | Unique: 24


==========================================================================================
                                        HOTSPOTID
==========================================================================================
Data Type: object | Unique Values: 82
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00% | Unique: 23
df6   → Rows: 26087   | Nulls: 953    | Missing %:   3.65% | Unique: 82
df7   → Rows: 26088   | Nulls: 953    | Missing %:   3.65% | Unique: 82
df8   → Rows: 26090   | Nulls: 955    | Missing %:   3.66% | Unique: 82
df9   → Rows: 26088   | Nulls: 953    | Missing %:   3.65% | Unique: 82


==========================================================================================
                                        RETAILERID
==========================================================================================
Data Type: object | Unique Values: 26088
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00% | Unique: 734
df6   → Rows: 26087   | Nulls: 0      | Missing %:   0.00% | Unique: 26087
df7   → Rows: 26088   | Nulls: 0      | Missing %:   0.00% | Unique: 26088
df8   → Rows: 26090   | Nulls: 2      | Missing %:   0.01% | Unique: 26088
df9   → Rows: 26088   | Nulls: 0      | Missing %:   0.00% | Unique: 26088


==========================================================================================
                                         SHOPTYPE
==========================================================================================
Data Type: object | Unique Values: 13
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 3      | Missing %:   0.41% | Unique: 11
df6   → Rows: 26087   | Nulls: 940    | Missing %:   3.60% | Unique: 13
df7   → Rows: 26088   | Nulls: 940    | Missing %:   3.60% | Unique: 13
df8   → Rows: 26090   | Nulls: 942    | Missing %:   3.61% | Unique: 13
df9   → Rows: 26088   | Nulls: 940    | Missing %:   3.60% | Unique: 13


==========================================================================================
                                      CONTACTPERSON
==========================================================================================
Data Type: object | Unique Values: 8157
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00% | Unique: 683
df6   → Rows: 26087   | Nulls: 927    | Missing %:   3.55% | Unique: 8156
df7   → Rows: 26088   | Nulls: 927    | Missing %:   3.55% | Unique: 8157
df8   → Rows: 26090   | Nulls: 929    | Missing %:   3.56% | Unique: 8157
df9   → Rows: 26088   | Nulls: 927    | Missing %:   3.55% | Unique: 8157


==========================================================================================
                                          FNAME
==========================================================================================
Data Type: object | Unique Values: 20406
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00% | Unique: 720
df6   → Rows: 26087   | Nulls: 923    | Missing %:   3.54% | Unique: 20405
df7   → Rows: 26088   | Nulls: 923    | Missing %:   3.54% | Unique: 20406
df8   → Rows: 26090   | Nulls: 925    | Missing %:   3.55% | Unique: 20406
df9   → Rows: 26088   | Nulls: 923    | Missing %:   3.54% | Unique: 20406


==========================================================================================
                                         MOBILENO
==========================================================================================
Data Type: object | Unique Values: 13929
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 31     | Missing %:   4.22% | Unique: 690
df6   → Rows: 26087   | Nulls: 8387   | Missing %:  32.15% | Unique: 13938
df7   → Rows: 26088   | Nulls: 8387   | Missing %:  32.15% | Unique: 13939
df8   → Rows: 26090   | Nulls: 8389   | Missing %:  32.15% | Unique: 13857
df9   → Rows: 26088   | Nulls: 8387   | Missing %:  32.15% | Unique: 13929


==========================================================================================
                                        LANDLINENO
==========================================================================================
Data Type: object | Unique Values: 11347
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 30     | Missing %:   4.09% | Unique: 691
df6   → Rows: 26087   | Nulls: 4887   | Missing %:  18.73% | Unique: 11198
df7   → Rows: 26088   | Nulls: 4887   | Missing %:  18.73% | Unique: 11061
df8   → Rows: 26090   | Nulls: 4889   | Missing %:  18.74% | Unique: 10990
df9   → Rows: 26088   | Nulls: 4887   | Missing %:  18.73% | Unique: 11347


==========================================================================================
                                         HOUSENO
==========================================================================================
Data Type: object | Unique Values: 8014
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 24     | Missing %:   3.27% | Unique: 522
df6   → Rows: 26087   | Nulls: 1054   | Missing %:   4.04% | Unique: 8089
df7   → Rows: 26088   | Nulls: 1054   | Missing %:   4.04% | Unique: 8089
df8   → Rows: 26090   | Nulls: 1056   | Missing %:   4.05% | Unique: 8027
df9   → Rows: 26088   | Nulls: 1054   | Missing %:   4.04% | Unique: 8014


==========================================================================================
                                          STREET
==========================================================================================
Data Type: object | Unique Values: 12096
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00% | Unique: 554
df6   → Rows: 26087   | Nulls: 926    | Missing %:   3.55% | Unique: 12096
df7   → Rows: 26088   | Nulls: 926    | Missing %:   3.55% | Unique: 12096
df8   → Rows: 26090   | Nulls: 928    | Missing %:   3.56% | Unique: 12096
df9   → Rows: 26088   | Nulls: 926    | Missing %:   3.55% | Unique: 12096


==========================================================================================
                                           CITY
==========================================================================================
Data Type: object | Unique Values: 6103
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00% | Unique: 409
df6   → Rows: 26087   | Nulls: 924    | Missing %:   3.54% | Unique: 6103
df7   → Rows: 26088   | Nulls: 924    | Missing %:   3.54% | Unique: 6103
df8   → Rows: 26090   | Nulls: 926    | Missing %:   3.55% | Unique: 6103
df9   → Rows: 26088   | Nulls: 924    | Missing %:   3.54% | Unique: 6103


==========================================================================================
                                         POSTCODE
==========================================================================================
Data Type: object | Unique Values: 2909
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00% | Unique: 260
df6   → Rows: 26087   | Nulls: 924    | Missing %:   3.54% | Unique: 1897
df7   → Rows: 26088   | Nulls: 924    | Missing %:   3.54% | Unique: 1897
df8   → Rows: 26090   | Nulls: 926    | Missing %:   3.55% | Unique: 1825
df9   → Rows: 26088   | Nulls: 924    | Missing %:   3.54% | Unique: 2909


==========================================================================================
                                          EMAIL
==========================================================================================
Data Type: object | Unique Values: 5885
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 98     | Missing %:  13.35% | Unique: 622
df6   → Rows: 26087   | Nulls: 19447  | Missing %:  74.55% | Unique: 5884
df7   → Rows: 26088   | Nulls: 19447  | Missing %:  74.54% | Unique: 5885
df8   → Rows: 26090   | Nulls: 19449  | Missing %:  74.55% | Unique: 5884
df9   → Rows: 26088   | Nulls: 19447  | Missing %:  74.54% | Unique: 5885


==========================================================================================
                                          VAT_NO
==========================================================================================
Data Type: object | Unique Values: 1823
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 497    | Missing %:  67.71% | Unique: 231
df6   → Rows: 26087   | Nulls: 24140  | Missing %:  92.54% | Unique: 1816
df7   → Rows: 26088   | Nulls: 24140  | Missing %:  92.53% | Unique: 1816
df8   → Rows: 26090   | Nulls: 24142  | Missing %:  92.53% | Unique: 1818
df9   → Rows: 26088   | Nulls: 24140  | Missing %:  92.53% | Unique: 1823


==========================================================================================
                                          RETID
==========================================================================================
Data Type: float64 | Unique Values: 6834
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 519    | Missing %:  70.71% | Unique: 215
df6   → Rows: 26087   | Nulls: 19253  | Missing %:  73.80% | Unique: 6834
df7   → Rows: 26088   | Nulls: 19254  | Missing %:  73.80% | Unique: 6834
df8   → Rows: 26090   | Nulls: 19256  | Missing %:  73.81% | Unique: 6834
df9   → Rows: 26088   | Nulls: 19254  | Missing %:  73.80% | Unique: 6834


==========================================================================================
                                       RETAILERMODE
==========================================================================================
Data Type: object | Unique Values: 3
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00% | Unique: 3
df6   → Rows: 26087   | Nulls: 923    | Missing %:   3.54% | Unique: 3
df7   → Rows: 26088   | Nulls: 923    | Missing %:   3.54% | Unique: 3
df8   → Rows: 26090   | Nulls: 925    | Missing %:   3.55% | Unique: 3
df9   → Rows: 26088   | Nulls: 923    | Missing %:   3.54% | Unique: 3


==========================================================================================
                                     RETAILER_STATUS
==========================================================================================
Data Type: object | Unique Values: 2
------------------------------------------------------------------------------------------
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00% | Unique: 2
df6   → Rows: 26087   | Nulls: 923    | Missing %:   3.54% | Unique: 2
df7   → Rows: 26088   | Nulls: 923    | Missing %:   3.54% | Unique: 2
df8   → Rows: 26090   | Nulls: 925    | Missing %:   3.55% | Unique: 2
df9   → Rows: 26088   | Nulls: 923    | Missing %:   3.54% | Unique: 2


==========================================================================================
                                     RETAILER_MSISDN
==========================================================================================
Data Type: float64 | Unique Values: 13383

In [48]:
# Let's assume your DataFrames are named df5, df6, df7, df8, df9

dataframes = {
    'df5': df5,
    'df6': df6,
    'df7': df7,
    'df8': df8,
    'df9': df9
}

# Loop through each column (assuming all dataframes share the same columns)
for column in df9.columns:
    print("=" * 110)
    print(f"{column:^110}")   # nicely centered column name
    print("=" * 110)
    
    for name, df in dataframes.items():
        total_rows = len(df)
        dtype = df[column].dtype
        unique_values = df[column].nunique(dropna=True)
        null_count = df[column].isnull().sum()
        null_percent = (null_count / total_rows) * 100
        
        print(f"{name:<5} → Rows: {total_rows:<7} |  Nulls: {null_count:<6} | "
              f"Missing %: {null_percent:6.2f}% | Dtype: {str(dtype):<10} | "
              f"Unique: {unique_values:<8}")  
    
    print("\n")

==============================================================================================================
                                        ISSUE1_INVALID RETAILER STATUS
==============================================================================================================
df5   → Rows: 734     |  Nulls: 423    | Missing %:  57.63% | Dtype: object     | Unique: 2
df6   → Rows: 26087   |  Nulls: 22892  | Missing %:  87.75% | Dtype: object     | Unique: 2
df7   → Rows: 26088   |  Nulls: 22893  | Missing %:  87.75% | Dtype: object     | Unique: 2
df8   → Rows: 26090   |  Nulls: 22895  | Missing %:  87.75% | Dtype: object     | Unique: 2
df9   → Rows: 26088   |  Nulls: 22894  | Missing %:  87.76% | Dtype: object     | Unique: 2


==============================================================================================================
                                         ISSUE2_INVALID RETAILER MODE
==============================================================================================================
df5   → Rows: 734     |  Nulls: 423    | Missing %:  57.63% | Dtype: object     | Unique: 2
df6   → Rows: 26087   |  Nulls: 22892  | Missing %:  87.75% | Dtype: object     | Unique: 2
df7   → Rows: 26088   |  Nulls: 22893  | Missing %:  87.75% | Dtype: object     | Unique: 2
df8   → Rows: 26090   |  Nulls: 22895  | Missing %:  87.75% | Dtype: object     | Unique: 2
df9   → Rows: 26088   |  Nulls: 22894  | Missing %:  87.76% | Dtype: object     | Unique: 2


==============================================================================================================
                                       ISSUE3_INVALID WHITELIST NUMBER
==============================================================================================================
df5   → Rows: 734     |  Nulls: 423    | Missing %:  57.63% | Dtype: object     | Unique: 1
df6   → Rows: 26087   |  Nulls: 22892  | Missing %:  87.75% | Dtype: object     | Unique: 1
df7   → Rows: 26088   |  Nulls: 22893  | Missing %:  87.75% | Dtype: object     | Unique: 1
df8   → Rows: 26090   |  Nulls: 22895  | Missing %:  87.75% | Dtype: object     | Unique: 1
df9   → Rows: 26088   |  Nulls: 22894  | Missing %:  87.76% | Dtype: object     | Unique: 1


==============================================================================================================
                                        ISSUE4_INVALID VIRTUAL NUMBER
==============================================================================================================
df5   → Rows: 734     |  Nulls: 423    | Missing %:  57.63% | Dtype: object     | Unique: 2
df6   → Rows: 26087   |  Nulls: 22892  | Missing %:  87.75% | Dtype: object     | Unique: 2
df7   → Rows: 26088   |  Nulls: 22893  | Missing %:  87.75% | Dtype: object     | Unique: 2
df8   → Rows: 26090   |  Nulls: 22895  | Missing %:  87.75% | Dtype: object     | Unique: 2
df9   → Rows: 26088   |  Nulls: 22894  | Missing %:  87.76% | Dtype: object     | Unique: 2


==============================================================================================================
                                              ISSUE5_SIM BLOCKED
==============================================================================================================
df5   → Rows: 734     |  Nulls: 423    | Missing %:  57.63% | Dtype: object     | Unique: 2
df6   → Rows: 26087   |  Nulls: 22892  | Missing %:  87.75% | Dtype: object     | Unique: 2
df7   → Rows: 26088   |  Nulls: 22893  | Missing %:  87.75% | Dtype: object     | Unique: 2
df8   → Rows: 26090   |  Nulls: 22895  | Missing %:  87.75% | Dtype: object     | Unique: 2
df9   → Rows: 26088   |  Nulls: 22894  | Missing %:  87.76% | Dtype: object     | Unique: 2


==============================================================================================================
                                                  STARTDATE
==============================================================================================================
df5   → Rows: 734     |  Nulls: 0      | Missing %:   0.00% | Dtype: int64      | Unique: 1
df6   → Rows: 26087   |  Nulls: 0      | Missing %:   0.00% | Dtype: int64      | Unique: 1
df7   → Rows: 26088   |  Nulls: 0      | Missing %:   0.00% | Dtype: int64      | Unique: 1
df8   → Rows: 26090   |  Nulls: 2      | Missing %:   0.01% | Dtype: float64    | Unique: 1
df9   → Rows: 26088   |  Nulls: 0      | Missing %:   0.00% | Dtype: int64      | Unique: 1


==============================================================================================================
                                                   ENDDATE
==============================================================================================================
df5   → Rows: 734     |  Nulls: 0      | Missing %:   0.00% | Dtype: int64      | Unique: 1
df6   → Rows: 26087   |  Nulls: 0      | Missing %:   0.00% | Dtype: int64      | Unique: 1
df7   → Rows: 26088   |  Nulls: 0      | Missing %:   0.00% | Dtype: int64      | Unique: 1
df8   → Rows: 26090   |  Nulls: 2      | Missing %:   0.01% | Dtype: float64    | Unique: 1
df9   → Rows: 26088   |  Nulls: 0      | Missing %:   0.00% | Dtype: int64      | Unique: 1


==============================================================================================================
                                                  CREATEDBY
==============================================================================================================
df5   → Rows: 734     |  Nulls: 1      | Missing %:   0.14% | Dtype: object     | Unique: 72
df6   → Rows: 26087   |  Nulls: 6121   | Missing %:  23.46% | Dtype: object     | Unique: 159
df7   → Rows: 26088   |  Nulls: 6121   | Missing %:  23.46% | Dtype: object     | Unique: 159
df8   → Rows: 26090   |  Nulls: 6123   | Missing %:  23.47% | Dtype: object     | Unique: 159
df9   → Rows: 26088   |  Nulls: 6121   | Missing %:  23.46% | Dtype: object     | Unique: 159


==============================================================================================================
                                                DATEOFCREATION
==============================================================================================================
df5   → Rows: 734     |  Nulls: 0      | Missing %:   0.00% | Dtype: object     | Unique: 504
df6   → Rows: 26087   |  Nulls: 923    | Missing %:   3.54% | Dtype: object     | Unique: 1881
df7   → Rows: 26088   |  Nulls: 923    | Missing %:   3.54% | Dtype: object     | Unique: 1881
df8   → Rows: 26090   |  Nulls: 925    | Missing %:   3.55% | Dtype: object     | Unique: 1881
df9   → Rows: 26088   |  Nulls: 923    | Missing %:   3.54% | Dtype: object     | Unique: 1881


==============================================================================================================
                                                   OFFMGRID
==============================================================================================================
df5   → Rows: 734     |  Nulls: 0      | Missing %:   0.00% | Dtype: object     | Unique: 3
df6   → Rows: 26087   |  Nulls: 923    | Missing %:   3.54% | Dtype: object     | Unique: 9
df7   → Rows: 26088   |  Nulls: 923    | Missing %:   3.54% | Dtype: object     | Unique: 9
df8   → Rows: 26090   |  Nulls: 925    | Missing %:   3.55% | Dtype: object     | Unique: 9
df9   → Rows: 26088   |  Nulls: 923    | Missing %:   3.54% | Dtype: object     | Unique: 9


==============================================================================================================
                                                   ACCMGRID
==============================================================================================================
df5   → Rows: 734     |  Nulls: 1      | Missing %:   0.14% | Dtype: object     | Unique: 6
df6   → Rows: 26087   |  Nulls: 7007   | Missing %:  26.86% | Dtype: object     | Unique: 24
df7   → Rows: 26088   |  Nulls: 7007   | Missing %:  26.86% | Dtype: object     | Unique: 24
df8   → Rows: 26090   |  Nulls: 7009   | Missing %:  26.86% | Dtype: object     | Unique: 24
df9   → Rows: 26088   |  Nulls: 7007   | Missing %:  26.86% | Dtype: object     | Unique: 24


==============================================================================================================
                                                  HOTSPOTID
==============================================================================================================
df5   → Rows: 734     |  Nulls: 0      | Missing %:   0.00% | Dtype: object     | Unique: 23
df6   → Rows: 26087   |  Nulls: 953    | Missing %:   3.65% | Dtype: object     | Unique: 82
df7   → Rows: 26088   |  Nulls: 953    | Missing %:   3.65% | Dtype: object     | Unique: 82
df8   → Rows: 26090   |  Nulls: 955    | Missing %:   3.66% | Dtype: object     | Unique: 82
df9   → Rows: 26088   |  Nulls: 953    | Missing %:   3.65% | Dtype: object     | Unique: 82


==============================================================================================================
                                                  RETAILERID
==============================================================================================================
df5   → Rows: 734     |  Nulls: 0      | Missing %:   0.00% | Dtype: object     | Unique: 734
df6   → Rows: 26087   |  Nulls: 0      | Missing %:   0.00% | Dtype: object     | Unique: 26087
df7   → Rows: 26088   |  Nulls: 0      | Missing %:   0.00% | Dtype: object     | Unique: 26088
df8   → Rows: 26090   |  Nulls: 2      | Missing %:   0.01% | Dtype: object     | Unique: 26088
df9   → Rows: 26088   |  Nulls: 0      | Missing %:   0.00% | Dtype: object     | Unique: 26088


==============================================================================================================
                                                   SHOPTYPE
==============================================================================================================
df5   → Rows: 734     |  Nulls: 3      | Missing %:   0.41% | Dtype: object     | Unique: 11
df6   → Rows: 26087   |  Nulls: 940    | Missing %:   3.60% | Dtype: object     | Unique: 13
df7   → Rows: 26088   |  Nulls: 940    | Missing %:   3.60% | Dtype: object     | Unique: 13
df8   → Rows: 26090   |  Nulls: 942    | Missing %:   3.61% | Dtype: object     | Unique: 13
df9   → Rows: 26088   |  Nulls: 940    | Missing %:   3.60% | Dtype: object     | Unique: 13


==============================================================================================================
                                                CONTACTPERSON
==============================================================================================================
df5   → Rows: 734     |  Nulls: 0      | Missing %:   0.00% | Dtype: object     | Unique: 683
df6   → Rows: 26087   |  Nulls: 927    | Missing %:   3.55% | Dtype: object     | Unique: 8156
df7   → Rows: 26088   |  Nulls: 927    | Missing %:   3.55% | Dtype: object     | Unique: 8157
df8   → Rows: 26090   |  Nulls: 929    | Missing %:   3.56% | Dtype: object     | Unique: 8157
df9   → Rows: 26088   |  Nulls: 927    | Missing %:   3.55% | Dtype: object     | Unique: 8157


==============================================================================================================
                                                    FNAME
==============================================================================================================
df5   → Rows: 734     |  Nulls: 0      | Missing %:   0.00% | Dtype: object     | Unique: 720
df6   → Rows: 26087   |  Nulls: 923    | Missing %:   3.54% | Dtype: object     | Unique: 20405
df7   → Rows: 26088   |  Nulls: 923    | Missing %:   3.54% | Dtype: object     | Unique: 20406
df8   → Rows: 26090   |  Nulls: 925    | Missing %:   3.55% | Dtype: object     | Unique: 20406
df9   → Rows: 26088   |  Nulls: 923    | Missing %:   3.54% | Dtype: object     | Unique: 20406


==============================================================================================================
                                                   MOBILENO
==============================================================================================================
df5   → Rows: 734     |  Nulls: 31     | Missing %:   4.22% | Dtype: object     | Unique: 690
df6   → Rows: 26087   |  Nulls: 8387   | Missing %:  32.15% | Dtype: object     | Unique: 13938
df7   → Rows: 26088   |  Nulls: 8387   | Missing %:  32.15% | Dtype: object     | Unique: 13939
df8   → Rows: 26090   |  Nulls: 8389   | Missing %:  32.15% | Dtype: object     | Unique: 13857
df9   → Rows: 26088   |  Nulls: 8387   | Missing %:  32.15% | Dtype: object     | Unique: 13929


==============================================================================================================
                                                  LANDLINENO
==============================================================================================================
df5   → Rows: 734     |  Nulls: 30     | Missing %:   4.09% | Dtype: float64    | Unique: 691
df6   → Rows: 26087   |  Nulls: 4887   | Missing %:  18.73% | Dtype: object     | Unique: 11198
df7   → Rows: 26088   |  Nulls: 4887   | Missing %:  18.73% | Dtype: object     | Unique: 11061
df8   → Rows: 26090   |  Nulls: 4889   | Missing %:  18.74% | Dtype: object     | Unique: 10990
df9   → Rows: 26088   |  Nulls: 4887   | Missing %:  18.73% | Dtype: object     | Unique: 11347


==============================================================================================================
                                                   HOUSENO
==============================================================================================================
df5   → Rows: 734     |  Nulls: 24     | Missing %:   3.27% | Dtype: object     | Unique: 522
df6   → Rows: 26087   |  Nulls: 1054   | Missing %:   4.04% | Dtype: object     | Unique: 8089
df7   → Rows: 26088   |  Nulls: 1054   | Missing %:   4.04% | Dtype: object     | Unique: 8089
df8   → Rows: 26090   |  Nulls: 1056   | Missing %:   4.05% | Dtype: object     | Unique: 8027
df9   → Rows: 26088   |  Nulls: 1054   | Missing %:   4.04% | Dtype: object     | Unique: 8014


==============================================================================================================
                                                    STREET
==============================================================================================================
df5   → Rows: 734     |  Nulls: 0      | Missing %:   0.00% | Dtype: object     | Unique: 554
df6   → Rows: 26087   |  Nulls: 926    | Missing %:   3.55% | Dtype: object     | Unique: 12096
df7   → Rows: 26088   |  Nulls: 926    | Missing %:   3.55% | Dtype: object     | Unique: 12096
df8   → Rows: 26090   |  Nulls: 928    | Missing %:   3.56% | Dtype: object     | Unique: 12096
df9   → Rows: 26088   |  Nulls: 926    | Missing %:   3.55% | Dtype: object     | Unique: 12096


==============================================================================================================
                                                     CITY
==============================================================================================================
df5   → Rows: 734     |  Nulls: 0      | Missing %:   0.00% | Dtype: object     | Unique: 409
df6   → Rows: 26087   |  Nulls: 924    | Missing %:   3.54% | Dtype: object     | Unique: 6103
df7   → Rows: 26088   |  Nulls: 924    | Missing %:   3.54% | Dtype: object     | Unique: 6103
df8   → Rows: 26090   |  Nulls: 926    | Missing %:   3.55% | Dtype: object     | Unique: 6103
df9   → Rows: 26088   |  Nulls: 924    | Missing %:   3.54% | Dtype: object     | Unique: 6103


==============================================================================================================
                                                   POSTCODE
==============================================================================================================
df5   → Rows: 734     |  Nulls: 0      | Missing %:   0.00% | Dtype: int64      | Unique: 260
df6   → Rows: 26087   |  Nulls: 924    | Missing %:   3.54% | Dtype: object     | Unique: 1897
df7   → Rows: 26088   |  Nulls: 924    | Missing %:   3.54% | Dtype: object     | Unique: 1897
df8   → Rows: 26090   |  Nulls: 926    | Missing %:   3.55% | Dtype: object     | Unique: 1825
df9   → Rows: 26088   |  Nulls: 924    | Missing %:   3.54% | Dtype: object     | Unique: 2909


==============================================================================================================
                                                    EMAIL
==============================================================================================================
df5   → Rows: 734     |  Nulls: 98     | Missing %:  13.35% | Dtype: object     | Unique: 622
df6   → Rows: 26087   |  Nulls: 19447  | Missing %:  74.55% | Dtype: object     | Unique: 5884
df7   → Rows: 26088   |  Nulls: 19447  | Missing %:  74.54% | Dtype: object     | Unique: 5885
df8   → Rows: 26090   |  Nulls: 19449  | Missing %:  74.55% | Dtype: object     | Unique: 5884
df9   → Rows: 26088   |  Nulls: 19447  | Missing %:  74.54% | Dtype: object     | Unique: 5885


==============================================================================================================
                                                    VAT_NO
==============================================================================================================
df5   → Rows: 734     |  Nulls: 497    | Missing %:  67.71% | Dtype: object     | Unique: 231
df6   → Rows: 26087   |  Nulls: 24140  | Missing %:  92.54% | Dtype: object     | Unique: 1816
df7   → Rows: 26088   |  Nulls: 24140  | Missing %:  92.53% | Dtype: object     | Unique: 1816
df8   → Rows: 26090   |  Nulls: 24142  | Missing %:  92.53% | Dtype: object     | Unique: 1818
df9   → Rows: 26088   |  Nulls: 24140  | Missing %:  92.53% | Dtype: object     | Unique: 1823


==============================================================================================================
                                                    RETID
==============================================================================================================
df5   → Rows: 734     |  Nulls: 519    | Missing %:  70.71% | Dtype: float64    | Unique: 215
df6   → Rows: 26087   |  Nulls: 19253  | Missing %:  73.80% | Dtype: float64    | Unique: 6834
df7   → Rows: 26088   |  Nulls: 19254  | Missing %:  73.80% | Dtype: float64    | Unique: 6834
df8   → Rows: 26090   |  Nulls: 19256  | Missing %:  73.81% | Dtype: float64    | Unique: 6834
df9   → Rows: 26088   |  Nulls: 19254  | Missing %:  73.80% | Dtype: float64    | Unique: 6834


==============================================================================================================
                                                 RETAILERMODE
==============================================================================================================
df5   → Rows: 734     |  Nulls: 0      | Missing %:   0.00% | Dtype: object     | Unique: 3
df6   → Rows: 26087   |  Nulls: 923    | Missing %:   3.54% | Dtype: object     | Unique: 3
df7   → Rows: 26088   |  Nulls: 923    | Missing %:   3.54% | Dtype: object     | Unique: 3
df8   → Rows: 26090   |  Nulls: 925    | Missing %:   3.55% | Dtype: object     | Unique: 3
df9   → Rows: 26088   |  Nulls: 923    | Missing %:   3.54% | Dtype: object     | Unique: 3


==============================================================================================================
                                               RETAILER_STATUS
==============================================================================================================
df5   → Rows: 734     |  Nulls: 0      | Missing %:   0.00% | Dtype: object     | Unique: 2

In [50]:
# Let's assume your DataFrames are named df5, df6, df7, df8, df9

dataframes = {
    'df5': df5,
    'df6': df6,
    'df7': df7,
    'df8': df8,
    'df9': df9
}

# Loop through each column (assuming all dataframes share the same columns)
for column in df9.columns:
    print("=" * 120)
    print(f"{column:^120}")   # nicely centered column name
    print("=" * 120)
    
    for name, df in dataframes.items():
        total_rows = len(df)
        dtype = df[column].dtype
        unique_values = df[column].nunique(dropna=True)
        null_count = df[column].isnull().sum()
        null_percent = (null_count / total_rows) * 100

        # Check if numeric and count zeros
        zero_count = df[column].eq(0).sum() if dtype in ['float64', 'int64'] else "N/A"
        
        print(f"{name:<5} → Rows: {total_rows:<7} | Nulls: {null_count:<6} | "
              f"Missing %: {null_percent:6.2f}% | Dtype: {str(dtype):<8} | "
              f"Unique: {unique_values:<8} | Zero Count: {zero_count}")
    
    print("\n")

========================================================================================================================
                                             ISSUE1_INVALID RETAILER STATUS
========================================================================================================================
df5   → Rows: 734     | Nulls: 423    | Missing %:  57.63% | Dtype: object   | Unique: 2        | Zero Count: N/A
df6   → Rows: 26087   | Nulls: 22892  | Missing %:  87.75% | Dtype: object   | Unique: 2        | Zero Count: N/A
df7   → Rows: 26088   | Nulls: 22893  | Missing %:  87.75% | Dtype: object   | Unique: 2        | Zero Count: N/A
df8   → Rows: 26090   | Nulls: 22895  | Missing %:  87.75% | Dtype: object   | Unique: 2        | Zero Count: N/A
df9   → Rows: 26088   | Nulls: 22894  | Missing %:  87.76% | Dtype: object   | Unique: 2        | Zero Count: N/A


========================================================================================================================
                                              ISSUE2_INVALID RETAILER MODE
========================================================================================================================
df5   → Rows: 734     | Nulls: 423    | Missing %:  57.63% | Dtype: object   | Unique: 2        | Zero Count: N/A
df6   → Rows: 26087   | Nulls: 22892  | Missing %:  87.75% | Dtype: object   | Unique: 2        | Zero Count: N/A
df7   → Rows: 26088   | Nulls: 22893  | Missing %:  87.75% | Dtype: object   | Unique: 2        | Zero Count: N/A
df8   → Rows: 26090   | Nulls: 22895  | Missing %:  87.75% | Dtype: object   | Unique: 2        | Zero Count: N/A
df9   → Rows: 26088   | Nulls: 22894  | Missing %:  87.76% | Dtype: object   | Unique: 2        | Zero Count: N/A


========================================================================================================================
                                            ISSUE3_INVALID WHITELIST NUMBER
========================================================================================================================
df5   → Rows: 734     | Nulls: 423    | Missing %:  57.63% | Dtype: object   | Unique: 1        | Zero Count: N/A
df6   → Rows: 26087   | Nulls: 22892  | Missing %:  87.75% | Dtype: object   | Unique: 1        | Zero Count: N/A
df7   → Rows: 26088   | Nulls: 22893  | Missing %:  87.75% | Dtype: object   | Unique: 1        | Zero Count: N/A
df8   → Rows: 26090   | Nulls: 22895  | Missing %:  87.75% | Dtype: object   | Unique: 1        | Zero Count: N/A
df9   → Rows: 26088   | Nulls: 22894  | Missing %:  87.76% | Dtype: object   | Unique: 1        | Zero Count: N/A


========================================================================================================================
                                             ISSUE4_INVALID VIRTUAL NUMBER
========================================================================================================================
df5   → Rows: 734     | Nulls: 423    | Missing %:  57.63% | Dtype: object   | Unique: 2        | Zero Count: N/A
df6   → Rows: 26087   | Nulls: 22892  | Missing %:  87.75% | Dtype: object   | Unique: 2        | Zero Count: N/A
df7   → Rows: 26088   | Nulls: 22893  | Missing %:  87.75% | Dtype: object   | Unique: 2        | Zero Count: N/A
df8   → Rows: 26090   | Nulls: 22895  | Missing %:  87.75% | Dtype: object   | Unique: 2        | Zero Count: N/A
df9   → Rows: 26088   | Nulls: 22894  | Missing %:  87.76% | Dtype: object   | Unique: 2        | Zero Count: N/A


========================================================================================================================
                                                   ISSUE5_SIM BLOCKED
========================================================================================================================
df5   → Rows: 734     | Nulls: 423    | Missing %:  57.63% | Dtype: object   | Unique: 2        | Zero Count: N/A
df6   → Rows: 26087   | Nulls: 22892  | Missing %:  87.75% | Dtype: object   | Unique: 2        | Zero Count: N/A
df7   → Rows: 26088   | Nulls: 22893  | Missing %:  87.75% | Dtype: object   | Unique: 2        | Zero Count: N/A
df8   → Rows: 26090   | Nulls: 22895  | Missing %:  87.75% | Dtype: object   | Unique: 2        | Zero Count: N/A
df9   → Rows: 26088   | Nulls: 22894  | Missing %:  87.76% | Dtype: object   | Unique: 2        | Zero Count: N/A


========================================================================================================================
                                                       STARTDATE
========================================================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00% | Dtype: int64    | Unique: 1        | Zero Count: 0
df6   → Rows: 26087   | Nulls: 0      | Missing %:   0.00% | Dtype: int64    | Unique: 1        | Zero Count: 0
df7   → Rows: 26088   | Nulls: 0      | Missing %:   0.00% | Dtype: int64    | Unique: 1        | Zero Count: 0
df8   → Rows: 26090   | Nulls: 2      | Missing %:   0.01% | Dtype: float64  | Unique: 1        | Zero Count: 0
df9   → Rows: 26088   | Nulls: 0      | Missing %:   0.00% | Dtype: int64    | Unique: 1        | Zero Count: 0


========================================================================================================================
                                                        ENDDATE
========================================================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00% | Dtype: int64    | Unique: 1        | Zero Count: 0
df6   → Rows: 26087   | Nulls: 0      | Missing %:   0.00% | Dtype: int64    | Unique: 1        | Zero Count: 0
df7   → Rows: 26088   | Nulls: 0      | Missing %:   0.00% | Dtype: int64    | Unique: 1        | Zero Count: 0
df8   → Rows: 26090   | Nulls: 2      | Missing %:   0.01% | Dtype: float64  | Unique: 1        | Zero Count: 0
df9   → Rows: 26088   | Nulls: 0      | Missing %:   0.00% | Dtype: int64    | Unique: 1        | Zero Count: 0


========================================================================================================================
                                                       CREATEDBY
========================================================================================================================
df5   → Rows: 734     | Nulls: 1      | Missing %:   0.14% | Dtype: object   | Unique: 72       | Zero Count: N/A
df6   → Rows: 26087   | Nulls: 6121   | Missing %:  23.46% | Dtype: object   | Unique: 159      | Zero Count: N/A
df7   → Rows: 26088   | Nulls: 6121   | Missing %:  23.46% | Dtype: object   | Unique: 159      | Zero Count: N/A
df8   → Rows: 26090   | Nulls: 6123   | Missing %:  23.47% | Dtype: object   | Unique: 159      | Zero Count: N/A
df9   → Rows: 26088   | Nulls: 6121   | Missing %:  23.46% | Dtype: object   | Unique: 159      | Zero Count: N/A


========================================================================================================================
                                                     DATEOFCREATION
========================================================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00% | Dtype: object   | Unique: 504      | Zero Count: N/A
df6   → Rows: 26087   | Nulls: 923    | Missing %:   3.54% | Dtype: object   | Unique: 1881     | Zero Count: N/A
df7   → Rows: 26088   | Nulls: 923    | Missing %:   3.54% | Dtype: object   | Unique: 1881     | Zero Count: N/A
df8   → Rows: 26090   | Nulls: 925    | Missing %:   3.55% | Dtype: object   | Unique: 1881     | Zero Count: N/A
df9   → Rows: 26088   | Nulls: 923    | Missing %:   3.54% | Dtype: object   | Unique: 1881     | Zero Count: N/A


========================================================================================================================
                                                        OFFMGRID
========================================================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00% | Dtype: object   | Unique: 3        | Zero Count: N/A
df6   → Rows: 26087   | Nulls: 923    | Missing %:   3.54% | Dtype: object   | Unique: 9        | Zero Count: N/A
df7   → Rows: 26088   | Nulls: 923    | Missing %:   3.54% | Dtype: object   | Unique: 9        | Zero Count: N/A
df8   → Rows: 26090   | Nulls: 925    | Missing %:   3.55% | Dtype: object   | Unique: 9        | Zero Count: N/A
df9   → Rows: 26088   | Nulls: 923    | Missing %:   3.54% | Dtype: object   | Unique: 9        | Zero Count: N/A


========================================================================================================================
                                                        ACCMGRID
========================================================================================================================
df5   → Rows: 734     | Nulls: 1      | Missing %:   0.14% | Dtype: object   | Unique: 6        | Zero Count: N/A
df6   → Rows: 26087   | Nulls: 7007   | Missing %:  26.86% | Dtype: object   | Unique: 24       | Zero Count: N/A
df7   → Rows: 26088   | Nulls: 7007   | Missing %:  26.86% | Dtype: object   | Unique: 24       | Zero Count: N/A
df8   → Rows: 26090   | Nulls: 7009   | Missing %:  26.86% | Dtype: object   | Unique: 24       | Zero Count: N/A
df9   → Rows: 26088   | Nulls: 7007   | Missing %:  26.86% | Dtype: object   | Unique: 24       | Zero Count: N/A


========================================================================================================================
                                                       HOTSPOTID
========================================================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00% | Dtype: object   | Unique: 23       | Zero Count: N/A
df6   → Rows: 26087   | Nulls: 953    | Missing %:   3.65% | Dtype: object   | Unique: 82       | Zero Count: N/A
df7   → Rows: 26088   | Nulls: 953    | Missing %:   3.65% | Dtype: object   | Unique: 82       | Zero Count: N/A
df8   → Rows: 26090   | Nulls: 955    | Missing %:   3.66% | Dtype: object   | Unique: 82       | Zero Count: N/A
df9   → Rows: 26088   | Nulls: 953    | Missing %:   3.65% | Dtype: object   | Unique: 82       | Zero Count: N/A


========================================================================================================================
                                                       RETAILERID
========================================================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00% | Dtype: object   | Unique: 734      | Zero Count: N/A
df6   → Rows: 26087   | Nulls: 0      | Missing %:   0.00% | Dtype: object   | Unique: 26087    | Zero Count: N/A
df7   → Rows: 26088   | Nulls: 0      | Missing %:   0.00% | Dtype: object   | Unique: 26088    | Zero Count: N/A
df8   → Rows: 26090   | Nulls: 2      | Missing %:   0.01% | Dtype: object   | Unique: 26088    | Zero Count: N/A
df9   → Rows: 26088   | Nulls: 0      | Missing %:   0.00% | Dtype: object   | Unique: 26088    | Zero Count: N/A


========================================================================================================================
                                                        SHOPTYPE
========================================================================================================================
df5   → Rows: 734     | Nulls: 3      | Missing %:   0.41% | Dtype: object   | Unique: 11       | Zero Count: N/A
df6   → Rows: 26087   | Nulls: 940    | Missing %:   3.60% | Dtype: object   | Unique: 13       | Zero Count: N/A
df7   → Rows: 26088   | Nulls: 940    | Missing %:   3.60% | Dtype: object   | Unique: 13       | Zero Count: N/A
df8   → Rows: 26090   | Nulls: 942    | Missing %:   3.61% | Dtype: object   | Unique: 13       | Zero Count: N/A
df9   → Rows: 26088   | Nulls: 940    | Missing %:   3.60% | Dtype: object   | Unique: 13       | Zero Count: N/A


========================================================================================================================
                                                     CONTACTPERSON
========================================================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00% | Dtype: object   | Unique: 683      | Zero Count: N/A
df6   → Rows: 26087   | Nulls: 927    | Missing %:   3.55% | Dtype: object   | Unique: 8156     | Zero Count: N/A
df7   → Rows: 26088   | Nulls: 927    | Missing %:   3.55% | Dtype: object   | Unique: 8157     | Zero Count: N/A
df8   → Rows: 26090   | Nulls: 929    | Missing %:   3.56% | Dtype: object   | Unique: 8157     | Zero Count: N/A
df9   → Rows: 26088   | Nulls: 927    | Missing %:   3.55% | Dtype: object   | Unique: 8157     | Zero Count: N/A


========================================================================================================================
                                                         FNAME
========================================================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00% | Dtype: object   | Unique: 720      | Zero Count: N/A
df6   → Rows: 26087   | Nulls: 923    | Missing %:   3.54% | Dtype: object   | Unique: 20405    | Zero Count: N/A
df7   → Rows: 26088   | Nulls: 923    | Missing %:   3.54% | Dtype: object   | Unique: 20406    | Zero Count: N/A
df8   → Rows: 26090   | Nulls: 925    | Missing %:   3.55% | Dtype: object   | Unique: 20406    | Zero Count: N/A
df9   → Rows: 26088   | Nulls: 923    | Missing %:   3.54% | Dtype: object   | Unique: 20406    | Zero Count: N/A


========================================================================================================================
                                                        MOBILENO
========================================================================================================================
df5   → Rows: 734     | Nulls: 31     | Missing %:   4.22% | Dtype: object   | Unique: 690      | Zero Count: N/A
df6   → Rows: 26087   | Nulls: 8387   | Missing %:  32.15% | Dtype: object   | Unique: 13938    | Zero Count: N/A
df7   → Rows: 26088   | Nulls: 8387   | Missing %:  32.15% | Dtype: object   | Unique: 13939    | Zero Count: N/A
df8   → Rows: 26090   | Nulls: 8389   | Missing %:  32.15% | Dtype: object   | Unique: 13857    | Zero Count: N/A
df9   → Rows: 26088   | Nulls: 8387   | Missing %:  32.15% | Dtype: object   | Unique: 13929    | Zero Count: N/A


========================================================================================================================
                                                       LANDLINENO
========================================================================================================================
df5   → Rows: 734     | Nulls: 30     | Missing %:   4.09% | Dtype: float64  | Unique: 691      | Zero Count: 0
df6   → Rows: 26087   | Nulls: 4887   | Missing %:  18.73% | Dtype: object   | Unique: 11198    | Zero Count: N/A
df7   → Rows: 26088   | Nulls: 4887   | Missing %:  18.73% | Dtype: object   | Unique: 11061    | Zero Count: N/A
df8   → Rows: 26090   | Nulls: 4889   | Missing %:  18.74% | Dtype: object   | Unique: 10990    | Zero Count: N/A
df9   → Rows: 26088   | Nulls: 4887   | Missing %:  18.73% | Dtype: object   | Unique: 11347    | Zero Count: N/A


========================================================================================================================
                                                        HOUSENO
========================================================================================================================
df5   → Rows: 734     | Nulls: 24     | Missing %:   3.27% | Dtype: object   | Unique: 522      | Zero Count: N/A
df6   → Rows: 26087   | Nulls: 1054   | Missing %:   4.04% | Dtype: object   | Unique: 8089     | Zero Count: N/A
df7   → Rows: 26088   | Nulls: 1054   | Missing %:   4.04% | Dtype: object   | Unique: 8089     | Zero Count: N/A
df8   → Rows: 26090   | Nulls: 1056   | Missing %:   4.05% | Dtype: object   | Unique: 8027     | Zero Count: N/A
df9   → Rows: 26088   | Nulls: 1054   | Missing %:   4.04% | Dtype: object   | Unique: 8014     | Zero Count: N/A


========================================================================================================================
                                                         STREET
========================================================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00% | Dtype: object   | Unique: 554      | Zero Count: N/A
df6   → Rows: 26087   | Nulls: 926    | Missing %:   3.55% | Dtype: object   | Unique: 12096    | Zero Count: N/A
df7   → Rows: 26088   | Nulls: 926    | Missing %:   3.55% | Dtype: object   | Unique: 12096    | Zero Count: N/A
df8   → Rows: 26090   | Nulls: 928    | Missing %:   3.56% | Dtype: object   | Unique: 12096    | Zero Count: N/A
df9   → Rows: 26088   | Nulls: 926    | Missing %:   3.55% | Dtype: object   | Unique: 12096    | Zero Count: N/A


========================================================================================================================
                                                          CITY
========================================================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00% | Dtype: object   | Unique: 409      | Zero Count: N/A
df6   → Rows: 26087   | Nulls: 924    | Missing %:   3.54% | Dtype: object   | Unique: 6103     | Zero Count: N/A
df7   → Rows: 26088   | Nulls: 924    | Missing %:   3.54% | Dtype: object   | Unique: 6103     | Zero Count: N/A
df8   → Rows: 26090   | Nulls: 926    | Missing %:   3.55% | Dtype: object   | Unique: 6103     | Zero Count: N/A
df9   → Rows: 26088   | Nulls: 924    | Missing %:   3.54% | Dtype: object   | Unique: 6103     | Zero Count: N/A


========================================================================================================================
                                                        POSTCODE
========================================================================================================================
df5   → Rows: 734     | Nulls: 0      | Missing %:   0.00% | Dtype: int64    | Unique: 260      | Zero Count: 0
df6   → Rows: 26087   | Nulls: 924    | Missing %:   3.54% | Dtype: object   | Unique: 1897     | Zero Count: N/A
df7   → Rows: 26088   | Nulls: 924    | Missing %:   3.54% | Dtype: object   | Unique: 1897     | Zero Count: N/A
df8   → Rows: 26090   | Nulls: 926    | Missing %:   3.55% | Dtype: object   | Unique: 1825     | Zero Count: N/A
df9   → Rows: 26088   | Nulls: 924    | Missing %:   3.54% | Dtype: object   | Unique: 2909     | Zero Count: N/A


========================================================================================================================
                                                         EMAIL
========================================================================================================================
df5   → Rows: 734     | Nulls: 98     | Missing %:  13.35% | Dtype: object   | Unique: 622      | Zero Count: N/A
df6   → Rows: 26087   | Nulls: 19447  | Missing %:  74.55% | Dtype: object   | Unique: 5884     | Zero Count: N/A